server:
  port: 8081

spring:
  application:
    name: pm
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/mis
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**