version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-server
    environment:
      POSTGRES_PASSWORD: 1!minsoopo
    volumes:
      - /Users/jeongminsu/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

